---
version: "3"
services:
  dev_r2d2-bot:
    hostname: "commander"
    container_name: "commander"
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/Berlin"
      - "UMASK=022"
      - "TERM=xterm"
    image: "ghcr.io/cyb3rgh05t/dev_r2d2-bot:latest"
    restart: "unless-stopped"
    volumes:
      - "/opt/appdata/dev_r2d2-bot/config:/usr/src/bot/structures/config:rw"
