---
version: "3"
services:
  discordbot:
    hostname: "discordbot"
    container_name: "discordbot"
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/Berlin"
      - "UMASK=022"
      - "TERM=xterm"
    image: "ghcr.io/cyb3rgh05t/mr.streamnet:latest"
    restart: "unless-stopped"
    volumes:
      - "/opt/appdata/discordbot/config:/usr/src/bot/src/config:rw"
